[
        (arguments)
        (comment)
        (do_statement)
        (elseif_statement)
        (else_statement)
        (for_statement)
        (function_declaration)
        (function_definition)
        (if_statement)
        (parameters)
        (repeat_statement)
        (table_constructor)
        (while_statement)
 ] @fold
