return {
        cmd          = { "harper-ls", "--stdio" },
        filetypes    = {
                "cs",
                "gitcommit",
                "html",
                "java",
                "javascript",
                "markdown",
                "nix",
                "python",
                "ruby",
                "rust",
                "swift",
                "typescript",
                "typescriptreact",
                "haskell",
                "cmake",
                "typst",
                "php",
                "dart",
                "clojure",
        },
        root_markers = { ".git" },
}
