local colors = Colors.Darkppuccin

local customCol = function(C)
        return {

                --------------------------------------------------------------------------------------------------------
                -- BUILTINS

                ---[[
                DiagnosticVirtualTextError = { bg = colors.base },
                DiagnosticVirtualTextWarn  = { bg = colors.base },
                DiagnosticVirtualTextInfo  = { bg = colors.base },
                DiagnosticVirtualTextHint  = { bg = colors.base },
                DiagnosticError            = { bg = colors.crust },
                DiagnosticWarn             = { bg = colors.crust },
                DiagnosticInfo             = { bg = colors.crust },
                DiagnosticHint             = { bg = colors.crust },
                --]]
                DapBreakpoint              = { link = "DiagnosticUnderlineError" },
                DiagnosticUnderlineError   = { fg = colors.overlay1, bg = "#30212c" },
                DiagnosticUnderlineWarn    = { fg = colors.overlay1, bg = "#312e2d" },
                DiagnosticUnderlineInfo    = { fg = colors.overlay1, bg = "#202d36" },
                DiagnosticUnderlineHint    = { fg = colors.overlay1, bg = "#222e33" },
                -- DiagnosticUnnecessary            = { link = "LspInlayHint" },
                ActiveLineNumber           = { fg = colors.subtext0 },
                Boolean                    = { fg = colors.peach },
                borderStyle                = { fg = colors.crust, bg = colors.crust },
                Character                  = { fg = colors.green },
                -- ColorColumn                   = { bg = colors.},
                Comment                    = { fg = colors.surface2 },
                Conceal                    = { link = "Folded" },
                Conditional                = { fg = colors.sapphire, italic = false },
                Constant                   = { fg = colors.peach },
                CurSearch                  = { fg = colors.teal, bg = colors.base },
                -- CursorColumn                  = { bg = colors.},
                -- Cursor                           = { fg = colors.crust, bg = colors.red },
                CursorLine                 = { bg = colors.none },
                CursorLineNr               = { fg = colors.ivory },
                Define                     = { fg = colors.pink },
                Directory                  = { fg = colors.ivory },
                -- EndOfBuffer                   = { fg = colors.},
                Error                      = { fg = colors.red },
                ErrorMsg                   = { fg = colors.red },
                FloatBorder                = { fg = colors.mantle, bg = colors.mantle },
                FloatTitle                 = { fg = colors.sky },
                -- FoldColumn                    = {},
                FoldColumn                 = { link = "NonText" },
                Folded                     = { fg = colors.surface2, bg = colors.mantle },
                Function                   = { fg = colors.ivory },
                String                     = { fg = colors.green, bg = colors.crust },
                GitSignsAdd                = { fg = colors.yellow, bg = colors.crust },
                GitSignsChange             = { fg = colors.yellow, bg = colors.crust },
                GitSignsCurrentLineBlame   = { link = "NormalFloat" },
                GitSignsDelete             = { bg = colors.crust },
                GitSignsUntracked          = { fg = "#7c7157", bg = colors.crust },
                MiniDiffSignAdd            = { fg = colors.yellow },
                MiniDiffSignChange         = { fg = colors.yellow },
                MiniDiffSignDelete         = { fg = colors.red },
                Identifier                 = { fg = colors.flamingo },
                Include                    = { fg = colors.mauve },
                IncSearch                  = { link = "CurSearch" },
                Keyword                    = { fg = colors.yellow, bold = false },
                Label                      = { fg = colors.sky },
                LineNr                     = { link = "NonText" },
                Macro                      = { fg = colors.peach },
                MatchParen                 = { fg = colors.mauve, bg = colors.surface0, bold = true },
                NonText                    = { fg = colors.surface0 },
                Normal                     = { bg = colors.crust },
                NormalFloat                = { bg = colors.mantle },
                NormalNC                   = { link = "Normal" },
                Number                     = { fg = colors.peach },
                Pmenu                      = { bg = colors.mantle },
                PmenuSel                   = { link = "Visual" },
                PmenuSbar                  = { bg = colors.base },
                PmenuThumb                 = { bg = colors.surface0 },
                PreCondit                  = { link = "PreProc" },
                PreProc                    = { fg = colors.pink },
                Question                   = { fg = colors.teal },
                Repeat                     = { link = "Conditional" },
                Search                     = { fg = colors.teal, bg = colors.base, reverse = true, bold = true },
                SignColumn                 = { link = "NonText" },
                SpecialComment             = { link = "Special" },
                Special                    = { fg = colors.pink },
                SpecialKey                 = { link = "NonText" },
                SpellBad                   = { sp = colors.red, underline = true },
                SpellCap                   = { sp = colors.yellow, underline = true },
                SpellLocal                 = { sp = colors.blue, underline = true },
                SpellRare                  = { sp = colors.green, underline = true },
                Statement                  = { fg = colors.red },
                -- StatusLine                    = { fg = colors., bg = colors.},
                StorageClass               = { fg = colors.teal },
                Structure                  = { fg = colors.teal },
                -- Substitute                    = { fg = colors., bg = colors., bold = true },
                Title                      = { fg = colors.pink },
                -- Todo                          = { fg = colors., bold = true, italic = true },
                TSDefinitionUsage          = { link = "LspReferenceText" },
                TypeDef                    = { link = "Type" },
                Type                       = { link = "Keyword" },
                -- Underlined                    = { fg = colors., underline = true },
                VertSplit                  = { link = "NonText" },
                Visual                     = {  bg = colors.crust, bold = true },
                WarningMsg                 = { fg = colors.yellow },
                WildMenu                   = { bg = colors.mantle },
                WinSeparator               = { link = "LineNr" },
                -- Exception                        = { fg = colors.yellow },
                Exception                  = { fg = colors.yellow },
                markdownBlockquote         = { bg = colors.crust },

                --------------------------------------------------------------------------------------------------------
                -- TREESITTER

                ["@comment.todo"]               = { fg = colors.crust, bg = colors.rosewater, italic = false, bold = true }, -- TODO
                ["@comment.note"]               = { fg = colors.crust, bg = colors.blue, italic = false, bold = true },      -- NOTE
                ["@comment.hint"]               = { fg = colors.crust, bg = colors.sky, italic = false, bold = true },       -- HINT
                ["@comment.warning"]            = { fg = colors.crust, bg = colors.yellow, italic = false, bold = true },    -- WARNING
                ["@comment.error"]              = { fg = colors.crust, bg = colors.red, italic = false, bold = true },       -- ERROR
                ["@comment.code"]               = { fg = colors.teal, bg = colors.base, italic = false, bold = false },      -- code
                ["@annotation"]                 = { fg = colors.yellow },
                ["@attribute"]                  = { fg = colors.teal },
                ["@boolean"]                    = { fg = colors.peach },
                ["@character"]                  = { fg = colors.green },
                ["@conditional"]                = { fg = colors.sapphire, italic = true },
                ["@constant.builtin"]           = { fg = colors.peach },
                ["@constant"]                   = { fg = colors.peach },
                ["@constant.macro"]             = { fg = colors.peach },
                ["@constructor"]                = { fg = colors.sky },
                ["@error"]                      = { fg = colors.red },
                ["@field"]                      = { fg = colors.lavender },
                ["@function"]                   = { fg = colors.ivory },
                ["@function.macro"]             = { fg = colors.teal },
                ["@function.method.call"]       = { fg = colors.ivory },
                ["@function.method"]            = { fg = colors.ivory },
                ["@keyword.exception"]          = { fg = colors.red },
                ["@keyword"]                    = { fg = colors.yellow, italic = true },
                ["@keyword.function"]           = { fg = colors.ivory },
                ["@keyword.function.ruby"]      = { fg = colors.ivory },
                ["@keyword.include"]            = { fg = colors.mauve },
                ["@keyword.operator"]           = { link = "@keyword.conditional" },
                ["@keyword.return"]             = { fg = colors.red },
                ["@label"]                      = { fg = colors.sapphire },
                -- ["@markup.emphasis"]          = { fg = colors., italic = true },
                ["@markup"]                     = { fg = colors.text },
                -- ["@markup.heading"]           = { fg = colors., bold = true },
                -- ["@markup.link"]              = { fg = colors., bold = true },
                ["@markup.link.url"]            = { fg = colors.teal, italic = true },
                ["@markup.list"]                = { fg = colors.pink },
                ["@markup.raw"]                 = { fg = colors.teal },
                ["@markup.strong"]              = { fg = colors.maroon, bold = true },
                ["@markup.underline"]           = { fg = colors.peach },
                ["@method"]                     = { fg = colors.ivory },
                ["@namespace"]                  = { fg = colors.ivory },
                ["@number.float"]               = { link = "Number" },
                ["@number"]                     = { link = "Number" },
                ["@punctuation.bracket"]        = { link = "Comment" },
                ["@punctuation.delimiter"]      = { link = "Comment" },
                ["@string.escape"]              = { fg = colors.pink },
                ["@string"]                     = { fg = colors.green },
                ["@string.regexp"]              = { fg = colors.peach },
                ["@string.special.symbol"]      = { fg = colors.flamingo },
                ["@string.special.url"]         = { fg = colors.pink },
                ["@string.special.url.comment"] = { fg = colors.pink },
                ["@string.special.url.html"]    = { fg = colors.pink },
                ["@structure"]                  = { fg = colors.teal },
                ["@tag.attribute"]              = { fg = colors.teal },
                ["@tag.delimiter"]              = { fg = colors.sky },
                ["@tag"]                        = { fg = colors.red },
                ["@type.builtin"]               = { fg = colors.yellow },
                ["@type"]                       = { link = "Comment" },
                ["@type.qualifier"]             = { fg = colors.mauve },
                ["@variable.builtin"]           = { fg = colors.red },
                ["@variable"]                   = { fg = colors.red },
                ["@variable.member"]            = { fg = colors.ivory },
                ["@variable.parameter"]         = { fg = colors.red },

                --------------------------------------------------------------------------------------------------------
                -- SEMANTIC TOKENS

                ["@module"]              = { fg = colors.yellow },
                ["@operator"]            = { fg = colors.sapphire },
                ["@property"]            = { fg = colors.lavender },
                ["@lsp.type.keyword"]    = { fg = colors.yellow, bg = "none" },
                ["@function.builtin"]    = { fg = colors.peach },
                ["@keyword.conditional"] = { link = "@conditional" },
                ["@keyword.repeat"]      = { link = "@conditional" },
                ["@class"]               = { fg = colors.teal },
                ["@decorator"]           = { fg = colors.peach },
                ["@enum"]                = { fg = colors.peach },
                ["@enumMember"]          = { fg = colors.peach },
                ["@event"]               = { fg = colors.yellow },
                ["@interface"]           = { fg = colors.teal },
                ["@lsp.type.class"]      = { fg = colors.teal },
                ["@lsp.type.decorator"]  = { fg = colors.peach },
                ["@lsp.type.enum"]       = { fg = colors.peach },
                ["@lsp.type.enumMember"] = { fg = colors.peach },
                ["@lsp.type.function"]   = { fg = colors.ivory },
                ["@lsp.type.interface"]  = { fg = colors.teal },
                ["@lsp.type.macro"]      = { fg = colors.peach },
                ["@lsp.type.method"]     = { fg = colors.ivory },
                ["@lsp.type.namespace"]  = { fg = colors.yellow },
                ["@lsp.type.parameter"]  = { fg = colors.maroon },
                ["@lsp.type.property"]   = { fg = colors.lavender },
                ["@lsp.type.struct"]     = { fg = colors.teal },
                ["@lsp.type.type"]       = { link = "Comment" },
                ["@lsp.type.variable"]   = { fg = colors.red },
                ["@modifier"]            = { fg = colors.mauve },
                ["@regexp"]              = { fg = colors.peach },
                ["@struct"]              = { fg = colors.teal },
                ["@typeParameter"]       = { fg = colors.yellow },

                --------------------------------------------------------------------------------------------------------
                -- C++

                cType              = { fg = colors.mauve },
                cppType            = { link = "cType" },
                cParen             = { link = "@lsp.type.bracket.cpp" },
                cBracket           = { link = "@lsp.type.bracket.cpp" },
                cBlock             = { fg = colors.red },
                cCommentStartError = { link = "Comment" },
                cRepeat            = { link = "@conditional" },
                cConditional       = { link = "@conditional" },
                cInclude           = { fg = colors.mauve },
                cDefine            = { fg = colors.mauve },
                cTypedef           = { link = "cType" },
                cppModifier        = { link = "@keyword" },

                -- ["@lsp.type.bracket.cpp"]                    = { link = "Comment" },
                ["@lsp.type.namespace.cpp"]                  = { fg = colors.yellow },
                ["@lsp.type.type.cpp"]                       = { link = "cppType" },
                ["@lsp.type.modifier.cpp"]                   = { link = "@conditional" },
                ["@type.builtin.cpp"]                        = { link = "cppType" },
                ["@keyword.operator.cpp"]                    = { link = "@operator" },
                ["@keyword.import.cpp"]                      = { link = "Preproc" },
                ["@keyword.conditional.cpp"]                 = { link = "@conditional" },
                ["@keyword.repeat.cpp"]                      = { link = "@conditional" },
                ["@keyword.return.cpp"]                      = { link = "@keyword.return" },
                -- ["@lsp.type.variable.cpp"]                   = { fg = colors.text },
                ["@function.cpp"]                            = { link = "Function" },
                ["@lsp.type.function.cpp"]                   = { link = "Function" },
                ["@lsp.type.method.cpp"]                     = { link = "Function" },
                ["@lsp.type.class.cpp"]                      = { link = "Function" },
                ["@lsp.typemod.class.defaultLibrary.cpp"]    = { link = "@class" },
                ["@lsp.typemod.variable.defaultLibrary.cpp"] = { link = "Function" },
                ["@lsp.typemod.function.defaultLibrary.cpp"] = { link = "Function" },
                ["@lsp.typemod.variable.globalScope"]        = { link = "Function" },
                ["@lsp.typemod.variable.functionScope.cpp"]  = { fg = colors.mauve },

                --------------------------------------------------------------------------------------------------------
                -- BLINK

                BlinkCmpKindClass         = { link = "@lsp.type.class" },
                BlinkCmpKindColor         = { link = "@define" },
                BlinkCmpKindConstant      = { link = "@constant" },
                BlinkCmpKindConstructor   = { link = "@constructor" },
                BlinkCmpKindEnum          = { link = "@lsp.type.enum" },
                BlinkCmpKindEnumMember    = { link = "@lsp.type.enumMember" },
                BlinkCmpKindEvent         = { link = "@lsp.type.event" },
                BlinkCmpKindField         = { link = "@lsp.type.property" },
                BlinkCmpKindFile          = { fg = colors.teal },
                BlinkCmpKindFolder        = { fg = colors.ivory },
                BlinkCmpKindFunction      = { link = "@lsp.type.function" },
                BlinkCmpKindInterface     = { link = "@lsp.type.interface" },
                BlinkCmpKindKeyword       = { fg = colors.rosewater },
                BlinkCmpKindMethod        = { link = "@lsp.type.method" },
                BlinkCmpKindModule        = { link = "@module" },
                BlinkCmpKindOperator      = { link = "@lsp.type.operator" },
                BlinkCmpKindProperty      = { link = "@lsp.type.property" },
                BlinkCmpKindReference     = { link = "@function.call" },
                BlinkCmpKindSnippet       = { link = "@module" },
                BlinkCmpKindStruct        = { link = "@lsp.type.struct" },
                BlinkCmpKindText          = { link = "@comment" },
                BlinkCmpKindTypeParameter = { link = "@lsp.type.typeParameter" },
                BlinkCmpKindUnit          = { link = "@module" },
                BlinkCmpKindValue         = { link = "@lsp.type.enumMember" },
                BlinkCmpKindVariable      = { link = "@lsp.type.type" },
                BlinkCmpAbbrDeprecated    = { link = "DiagnosticDeprecated" },

                BlinkCmpLabelDescription    = { link = "Comment" },
                BlinkCmpLabelDetail         = { link = "Comment" },
                BlinkCmpLabelMatch          = { link = "Normal" },
                -- BlinkCmpMenu             = { bg = "#13131E" },
                -- BlinkCmpMenu             = { bg = "#0e0e16" },
                -- BlinkCmpMenuBorder       = { fg = colors.mantle, bg = colors.mantle },
                BlinkCmpMenu                = { bg = colors.mantle },
                -- BlinkCmpMenu             = { bg = "#11111b" },
                -- BlinkCmpMenuBorder       = { fg = "#11111b", bg = "#11111b" },
                BlinkCmpMenuBorder          = { fg = colors.surface0, bg = colors.mantle },
                -- BlinkCmpMenuBorder       = { fg = colors.base, bg = colors.mantle },
                BlinkCmpDoc                 = { bg = colors.base },
                BlinkCmpDocBorder           = { bg = colors.base },
                BlinkCmpDocSeparator        = { bg = colors.base },
                -- BlinkCmpMenuSelection    = { link = "Visual" },
                BlinkCmpMenuSelection       = { bg = colors.base, bold = false },
                BlinkCmpSource              = { link = "Comment" },
                BlinkCmpScrollBarThumb      = { link = "PmenuThumb" },
                BlinkCmpScrollBarGutter     = { link = "PmenuSbar" },
                BlinkCmpSignatureHelp       = { bg = colors.base },
                BlinkCmpSignatureHelpBorder = { bg = colors.base },

                --------------------------------------------------------------------------------------------------------
                -- DROPBAR

                DropBarCurrentContext = { link = "Visual" },
                DropBarFzfMatch       = { link = "DiagnosticErrorMsg" },
                DropBarHover          = { link = "Visual" },

                --------------------------------------------------------------------------------------------------------
                -- DROPBAR ICON UI

                DropBarIconUiIndicator    = { link = "NonText" },
                DropBarIconUiSeparator    = { link = "Comment" },
                DropBarMenuCurrentContext = { link = "Visual" },
                DropBarMenuHoverEntry     = { link = "Visual" },
                DropBarMenuHoverIcon      = { link = "IncSearch" },
                DropBarMenuHoverSymbol    = { link = "Visual" },
                DropBarMenuFloatBorder    = { link = "FloatBorder" },
                DropBarMenuNormalFloat    = { link = "Normal" },
                DropBarMenuSbar           = { link = "PmenuSbar" },
                DropBarMenuThumb          = { link = "PmenuThumb" },

                --------------------------------------------------------------------------------------------------------
                -- DROPBAR KIND

                DropBarKindDefault           = { link = "@text" },
                DropBarKindArray             = { link = "@string" },
                DropBarKindBoolean           = { link = "@lsp.type.boolean" },
                DropBarKindBreakstatement    = { link = "DiagnosticError" },
                DropBarKindCall              = { link = "@function.call" },
                DropBarKindCasestatement     = { link = "Conditional" },
                DropBarKindClass             = { link = "@lsp.type.class" },
                DropBarKindConstant          = { link = "@constant" },
                DropBarKindConstructor       = { link = "@constructor" },
                DropBarKindContinuestatement = { link = "Conditional" },
                DropBarKindDeclaration       = { link = "@lsp.type.type" },
                DropBarKindDelete            = { link = "DiagnosticError" },
                DropBarKindDir               = { link = "Function" },
                DropBarKindDostatement       = { link = "@keyword" },
                DropBarKindElsestatement     = { link = "Conditional" },
                DropBarKindElement           = { link = "@variable.builtin" },
                DropBarKindEnum              = { link = "@lsp.type.enum" },
                DropBarKindEnumMember        = { link = "@lsp.type.enumMember" },
                DropBarKindEvent             = { link = "@lsp.type.event" },
                DropBarKindField             = { link = "@field" },
                DropBarKindFile              = { link = "Comment" },
                DropBarKindFolder            = { link = "Function" },
                DropBarKindForStatement      = { link = "@keyword.repeat" },
                DropBarKindFunction          = { link = "@lsp.type.function" },
                DropBarKindH1Marker          = { link = "MarkdownH1" },
                DropBarKindH2Marker          = { link = "MarkdownH2" },
                DropBarKindH3Marker          = { link = "MarkdownH3" },
                DropBarKindH4Marker          = { link = "MarkdownH4" },
                DropBarKindH5Marker          = { link = "MarkdownH5" },
                DropBarKindH6Marker          = { link = "MarkdownH6" },
                DropBarKindIdentifier        = { link = "Identifier" },
                DropBarKindIfStatement       = { link = "Conditional" },
                DropBarKindInterface         = { link = "@lsp.type.interface" },
                DropBarKindKeyword           = { link = "@lsp.type.keyword" },
                DropBarKindList              = { link = "@markup.list" },
                DropBarKindMacro             = { link = "@lsp.type.macro" },
                DropBarKindMarkdownH1        = { link = "MarkdownH1" },
                DropBarKindMarkdownH2        = { link = "MarkdownH2" },
                DropBarKindMarkdownH3        = { link = "MarkdownH3" },
                DropBarKindMarkdownH4        = { link = "MarkdownH4" },
                DropBarKindMarkdownH5        = { link = "MarkdownH5" },
                DropBarKindMarkdownH6        = { link = "MarkdownH6" },
                DropBarKindMethod            = { link = "@lsp.type.method" },
                DropBarKindModule            = { link = "@module" },
                DropBarKindNamespace         = { link = "@lsp.type.namespace" },
                DropBarKindNull              = { link = "@lsp.type.boolean" },
                DropBarKindNumber            = { link = "@lsp.type.number" },
                DropBarKindObject            = { link = "@keyword.function" },
                DropBarKindOperator          = { link = "@lsp.type.operator" },
                DropBarKindPackage           = { link = "Conditional" },
                DropBarKindPair              = { link = "@keyword" },
                DropBarKindProperty          = { link = "@property" },
                DropBarKindReference         = { link = "@keyword" },
                DropBarKindRepeat            = { link = "@keyword.repeat" },
                DropBarKindRuleset           = { link = "@include" },
                DropBarKindScope             = { link = "@include" },
                DropBarKindSpecifier         = { link = "@include" },
                DropBarKindStatement         = { link = "Statement" },
                DropBarKindString            = { link = "@string" },
                DropBarKindStruct            = { link = "@lsp.type.struct" },
                DropBarKindSwitchstatement   = { link = "Conditional" },
                DropBarKindTerminal          = { link = "@string" },
                DropBarKindType              = { link = "@lsp.type.type" },
                DropBarKindTypeParameter     = { link = "@lsp.type.typeParameter" },
                DropBarKindUnit              = { link = "@keyword" },
                DropBarKindValue             = { link = "@text" },
                DropBarKindVariable          = { link = "@lsp.type.variable" },
                DropBarKindWhileStatement    = { link = "@keyword.repeat" },

                --------------------------------------------------------------------------------------------------------
                -- DROPBAR ICON KIND

                DropBarIconKindDefault           = { link = "@text" },
                DropBarIconKindArray             = { link = "@string" },
                DropBarIconKindBoolean           = { link = "@lsp.type.boolean" },
                DropBarIconKindBreakstatement    = { link = "DiagnosticError" },
                DropBarIconKindCall              = { link = "@function.call" },
                DropBarIconKindCasestatement     = { link = "Conditional" },
                DropBarIconKindClass             = { link = "@lsp.type.class" },
                DropBarIconKindConstant          = { link = "@constant" },
                DropBarIconKindConstructor       = { link = "@constructor" },
                DropBarIconKindContinuestatement = { link = "Conditional" },
                DropBarIconKindDeclaration       = { link = "@lsp.type.type" },
                DropBarIconKindDelete            = { link = "DiagnosticError" },
                DropBarIconKindDir               = { link = "Function" },
                DropBarIconKindDostatement       = { link = "@keyword" },
                DropBarIconKindElsestatement     = { link = "Conditional" },
                DropBarIconKindElement           = { link = "@variable.builtin" },
                DropBarIconKindEnum              = { link = "@lsp.type.enum" },
                DropBarIconKindEnumMember        = { link = "@lsp.type.enumMember" },
                DropBarIconKindEvent             = { link = "@lsp.type.event" },
                DropBarIconKindField             = { link = "@field" },
                DropBarIconKindFile              = { link = "Comment" },
                DropBarIconKindFolder            = { link = "Function" },
                DropBarIconKindForStatement      = { link = "@keyword.repeat" },
                DropBarIconKindFunction          = { link = "@lsp.type.function" },
                DropBarIconKindH1Marker          = { link = "MarkdownH1" },
                DropBarIconKindH2Marker          = { link = "MarkdownH2" },
                DropBarIconKindH3Marker          = { link = "MarkdownH3" },
                DropBarIconKindH4Marker          = { link = "MarkdownH4" },
                DropBarIconKindH5Marker          = { link = "MarkdownH5" },
                DropBarIconKindH6Marker          = { link = "MarkdownH6" },
                DropBarIconKindIdentifier        = { link = "Identifier" },
                DropBarIconKindIfStatement       = { link = "Conditional" },
                DropBarIconKindInterface         = { link = "@lsp.type.interface" },
                DropBarIconKindKeyword           = { link = "@lsp.type.keyword" },
                DropBarIconKindList              = { link = "@markup.list" },
                DropBarIconKindMacro             = { link = "@lsp.type.macro" },
                DropBarIconKindMarkdownH1        = { link = "MarkdownH1" },
                DropBarIconKindMarkdownH2        = { link = "MarkdownH2" },
                DropBarIconKindMarkdownH3        = { link = "MarkdownH3" },
                DropBarIconKindMarkdownH4        = { link = "MarkdownH4" },
                DropBarIconKindMarkdownH5        = { link = "MarkdownH5" },
                DropBarIconKindMarkdownH6        = { link = "MarkdownH6" },
                DropBarIconKindMethod            = { link = "@lsp.type.method" },
                DropBarIconKindModule            = { link = "@module" },
                DropBarIconKindNamespace         = { link = "@lsp.type.namespace" },
                DropBarIconKindNull              = { link = "@lsp.type.boolean" },
                DropBarIconKindNumber            = { link = "@lsp.type.number" },
                DropBarIconKindObject            = { link = "@keyword.function" },
                DropBarIconKindOperator          = { link = "@lsp.type.operator" },
                DropBarIconKindPackage           = { link = "Conditional" },
                DropBarIconKindPair              = { link = "@keyword" },
                DropBarIconKindProperty          = { link = "@property" },
                DropBarIconKindReference         = { link = "@keyword" },
                DropBarIconKindRepeat            = { link = "@keyword.repeat" },
                DropBarIconKindRuleset           = { link = "@include" },
                DropBarIconKindScope             = { link = "@include" },
                DropBarIconKindSpecifier         = { link = "@include" },
                DropBarIconKindStatement         = { link = "Statement" },
                DropBarIconKindString            = { link = "@string" },
                DropBarIconKindStruct            = { link = "@lsp.type.struct" },
                DropBarIconKindSwitchstatement   = { link = "Conditional" },
                DropBarIconKindTerminal          = { link = "@string" },
                DropBarIconKindType              = { link = "@lsp.type.type" },
                DropBarIconKindTypeParameter     = { link = "@lsp.type.typeParameter" },
                DropBarIconKindUnit              = { link = "@keyword" },
                DropBarIconKindValue             = { link = "@text" },
                DropBarIconKindVariable          = { link = "@lsp.type.variable" },
                DropBarIconKindWhileStatement    = { link = "@keyword.repeat" },

                --------------------------------------------------------------------------------------------------------
                -- SNACKS

                SnacksBackdrop              = { bg = colors.none },
                SnacksTitle                 = { link = "DiagnosticError" },
                SnacksPickerTitle           = { link = "DiagnosticError" },
                SnacksPicker                = { link = "Normal" },
                SnacksPickerListCursorLine  = { link = "Visual" },
                SnacksPickerBorder          = { link = "borderStyle" },
                SnacksPickerCursorLine      = { link = "TinyInlineDiagnosticVirtualTextError" },
                SnacksPickerSelected        = { fg = colors.red },
                SnacksPickerIconFile        = { fg = colors.teal },
                SnacksNotifierBorderInfo    = { link = "TinyInlineDiagnosticVirtualTextInfo" },
                SnacksNotifierBorderWarn    = { link = "TinyInlineDiagnosticVirtualTextWarn" },
                SnacksNotifierBorderError   = { link = "TinyInlineDiagnosticVirtualTextError" },
                SnacksNotifierFooterInfo    = { link = "TinyInlineDiagnosticVirtualTextInfo" },
                SnacksNotifierFooterWarn    = { link = "TinyInlineDiagnosticVirtualTextWarn" },
                SnacksNotifierFooterError   = { link = "TinyInlineDiagnosticVirtualTextError" },
                SnacksNotifierTitleInfo     = { link = "TinyInlineDiagnosticVirtualTextInfo" },
                SnacksNotifierTitleWarn     = { link = "TinyInlineDiagnosticVirtualTextWarn" },
                SnacksNotifierTitleError    = { link = "TinyInlineDiagnosticVirtualTextError" },
                SnacksNotifierInfo          = { link = "TinyInlineDiagnosticVirtualTextInfo" },
                SnacksNotifierWarn          = { link = "TinyInlineDiagnosticVirtualTextWarn" },
                SnacksNotifierError         = { link = "TinyInlineDiagnosticVirtualTextError" },
                -- SnacksPickerFile                             = { fg = colors.teal },
                SnacksNotifierHistoryBorder = { fg = colors.spark },
                SnacksIndent                = { fg = colors.none },
                SnacksIndentBlank           = { fg = colors.none },

                --------------------------------------------------------------------------------------------------------
                -- NEOTREE

                NeoTreeCursorLine    = { link = "Visual" },
                NeoTreeFileName      = { link = "NonText" },
                NeoTreeGitModified   = { link = "GitSignsDelete" },
                NeoTreeGitUntracked  = { link = "GitsignsUntracked" },
                NeoTreeNormal        = { link = "Normal" },
                NeoTreeNormalNC      = { link = "NormalNC" },
                NeoTreeVertSplit     = { link = "WinSeparator" },
                NeoTreeWinSeparator  = { link = "WinSeparator" },
                NeoTreeStatsHeader   = { link = "Title" },
                NeoTreeFloatNormal   = { link = "NormalFloat" },
                NeoTreeDirectoryIcon = { fg = colors.ivory },
                NeoTreeDirectoryName = { fg = colors.ivory },
                NeoTreeFloatTitle    = { link = "Title" },
                NeoTreeTitleBar      = { link = "IncSearch" },
                NeoTreeFloatBorder   = { link = "NormalFloat" },
                NeoTreeModified      = { link = "Normal" },
                NeoTreeRootName      = { link = "CursorLineNr" },

                --------------------------------------------------------------------------------------------------------
                -- TELESCOPE

                TelescopePromptCount    = { link = "Normal" },
                TelescopePromptTitle    = { link = "DiagnosticError" },
                TelescopePromptPrefix   = { link = "DiagnosticError" },
                TelescopePromptNormal   = { link = "Normal" },
                TelescopePromptBorder   = { link = "FloatBorder" },
                TelescopeResultsTitle   = { link = "DiagnosticError" },
                TelescopeResultsNormal  = { link = "NonText" },
                TelescopeResultsBorder  = { link = "FloatBorder" },
                TelescopePreviewTitle   = { link = "DiagnosticError" },
                TelescopePreviewNormal  = { link = "Normal" },
                TelescopePreviewBorder  = { link = "FloatBorder" },
                TelescopeSelection      = { link = "Visual" },
                TelescopeSelectionCaret = { link = "Visual" },

                --------------------------------------------------------------------------------------------------------
                -- MINI-STATUSLINE

                MiniStatuslineModeNormal  = { bg = colors.text },
                MiniStatuslineModeInsert  = { bg = colors.text },
                MiniStatuslineModeVisual  = { bg = colors.text },
                MiniStatuslineModeOther   = { bg = colors.text },
                MiniStatuslineModeReplace = { bg = colors.text },
                MiniStatuslineModeCommand = { bg = colors.text },
                MiniStatuslineDevinfo     = { bg = colors.crust },
                MiniStatuslineFileinfo    = { bg = colors.crust },
                MiniStatuslineFilename    = { fg = colors.surface0, bg = colors.crust },
                MiniStatuslineInactive    = { fg = colors.text, bg = colors.crust },

                --------------------------------------------------------------------------------------------------------
                -- MINI-FILES

                MiniFilesDirectory  = { fg = colors.ivory },
                MiniFilesFile       = { link = "Comment" },
                MiniFilesCursorLine = { link = "Visual" },
                MiniFilesBorder     = { link = "FloatBorder" },

                --------------------------------------------------------------------------------------------------------
                -- MINI-HIPATTERNS

                MiniHipatternsNote  = { fg = colors.crust, bg = colors.sky, italic = true, bold = true },
                MiniHipatternsTodo  = { fg = colors.crust, bg = colors.teal, italic = true, bold = true },
                MiniHipatternsHack  = { fg = colors.crust, bg = colors.yellow, italic = true, bold = true },
                MiniHipatternsFixme = { fg = colors.crust, bg = colors.red, italic = true, bold = true },

                --------------------------------------------------------------------------------------------------------
                -- NOICE

                NoiceCmdline            = { link = "NormalFloat" },
                NoiceConfirm            = { link = "NormalFloat" },
                NoiceConfirmBorder      = { link = "FloatBorder" },
                NoiceCmdlinePopup       = { link = "NormalFloat" },
                NoiceCmdlinePopupBorder = { link = "FloatBorder" },
                NoiceCmdlineIcon        = { link = "Title" },

                --------------------------------------------------------------------------------------------------------
                -- MISC

                YaziFloatBorder         = { fg = colors.crust, bg = colors.crust },
                MoreMsg                 = { link = "DiagnosticHint" },
                LspInlayHint            = { bg = colors.base },
                SymbolUsage             = { bg = colors.base },
                FoldMark                = { link = "LspInlayHint" },
                LightBulbSign           = { link = "DiagnosticSignHint" },
                OutlineCurrent          = { bg = colors.base },
                OutlineDetails          = { link = "LspInlayHint" },
                OutlineFoldMarker       = { link = "Comment" },
                FlashBackdrop           = { link = "NonText" },
                FlashMatch              = { link = "LspInlayHint" },
                FlashCurrent            = { link = "LspInlayHint" },
                FlashLabel              = { link = "DiagnosticError" },
                TreesitterContext       = { bg = colors.mantle, bold = true },
                LspReferenceText        = { link = "Visual" },
                LspReferenceWrite       = { link = "LspReferenceText" },
                LspReferenceRead        = { link = "LspReferenceWrite" },
                DiffAdded               = { link = "DiffAdd" },
                DiffRemoved             = { link = "DiffDelete" },
                QuickFixLine            = { link = "Visual" },
                MasonNormal             = { bg = colors.mantle },
                MasonHeading            = { fg = colors.red, bg = colors.mantle, bold = false },
                MasonHeader             = { fg = colors.red, bg = colors.mantle, bold = false },
                MasonHighlight          = { fg = colors.teal, bg = colors.mantle, bold = false },
                MasonHighlightBlockBold = { fg = colors.spark, bg = colors.mantle, bold = false },
                MasonMutedBlock         = { fg = colors.surface1, bg = colors.mantle, bold = false },
        }
end

return {
        "catppuccin/nvim",
        lazy     = false,
        name     = "catppuccin",
        priority = 2000,
        config   = function()
                require("catppuccin").setup({
                        compile_path           = vim.fn.stdpath"cache" .. "/catppuccin",
                        flavour                = "mocha",
                        transparent_background = false,
                        show_end_of_buffer     = true,
                        term_colors            = true,
                        background             = { light = "latte", dark = "mocha" },
                        dim_inactive           = { enabled = false, shade = "dark", percentage = 0.15 },
                        no_italic              = true,
                        no_bold                = false,
                        no_underline           = true,
                        styles                 = { conditionals = { "italic" }, loops = { "italic" }, misc = {} },
                        color_overrides        = { mocha = { mantle = "#14141f", crust = "#0e0e16" } },
                        custom_highlights      = customCol,
                        default_integrations   = true,
                        auto_integrations      = false,
                        integrations           = {
                                blink_cmp        = true,
                                cmp              = true,
                                dap              = true,
                                dap_ui           = true,
                                dashboard        = true,
                                mason            = true,
                                markdown         = true,
                                render_markdown  = true,
                                mini             = true,
                                notify           = true,
                                neotree          = true,
                                semantic_tokens  = true,
                                treesitter       = true,
                                ufo              = true,
                                dropbar          = { enabled = true, color_mode = false },
                                indent_blankline = { enabled = true, scope_color = "text" },
                                native_lsp       = {
                                        enabled    = true,
                                        underlines = {
                                                errors      = { "nocombine" },
                                                hints       = { "nocombine" },
                                                warnings    = { "nocombine" },
                                                information = { "nocombine" },
                                                ok          = { "nocombine" },
                                        },
                                },
                        },
                })
        end,
}
