return {
        "dnlhc/glance.nvim",
        keys   = {
                { "<LocalLeader>r", desc = "Glance ref",     "<cmd>Glance references<CR>" },
                { "<LocalLeader>d", desc = "Glance def",     "<cmd>Glance definitions<CR>" },
                { "<LocalLeader>i", desc = "Glance impl",    "<cmd>Glance implementations<CR>" },
                { "<LocalLeader>D", desc = "Glance typedef", "<cmd>Glance type_definitions<CR>" },
                { "<LocalLeader>j", desc = "Glance resume",  "<cmd>Glance resume<CR>" },
        },
        opts   = {
                height               = 25,
                preserve_win_context = true,
                preview_win_opts     = { cursorline = false, number = false, wrap = false },
                border               = { enable = false, top_char = " ", bottom_char = " " },
                list                 = { width = 0.35 },
                indent_lines         = { enable = true, icon = " " },
                winbar               = { enable = false },
                mappings             = {
                        list    = {
                                ["j"]       = function() require("glance").actions.next() end,
                                ["k"]       = function() require("glance").actions.previous() end,
                                ["<Down>"]  = function() require("glance").actions.next() end,
                                ["<Up>"]    = function() require("glance").actions.previous() end,
                                ["<Tab>"]   = function() require("glance").actions.next_location() end,
                                ["<S-Tab>"] = function() require("glance").actions.previous_location() end,
                                ["<C-u>"]   = function() require("glance").actions.preview_scroll_win(5) end,
                                ["<C-d>"]   = function() require("glance").actions.preview_scroll_win(-5) end,
                                ["v"]       = function() require("glance").actions.jump_vsplit() end,
                                ["s"]       = function() require("glance").actions.jump_split() end,
                                ["t"]       = function() require("glance").actions.jump_tab() end,
                                ["<CR>"]    = function() require("glance").actions.jump() end,
                                ["o"]       = function() require("glance").actions.jump() end,
                                ["l"]       = function() require("glance").actions.open_fold() end,
                                ["h"]       = function() require("glance").actions.close_fold() end,
                                ["K"]       = function() require("glance").actions.enter_win("preview") end,
                                ["q"]       = function() require("glance").actions.close() end,
                                ["Q"]       = function() require("glance").actions.close() end,
                                ["<Esc>"]   = function() require("glance").actions.close() end,
                                ["<C-q>"]   = function() require("glance").actions.quickfix() end,
                        },
                        preview = {
                                ["Q"]       = function() require("glance").actions.close() end,
                                ["<Tab>"]   = function() require("glance").actions.next_location() end,
                                ["<S-Tab>"] = function() require("glance").actions.previous_location() end,
                                ["K"]       = function() require("glance").actions.enter_win("list") end,
                        },
                },
        },
        config = function(_, opts)
                require("glance").setup(opts)

                _G.hlLink({
                                  { "FoldIcon",            "Comment" },
                                  { "ListNormal",          "Normal" },
                                  { "ListFilename",        "Directory" },
                                  { "ListFilepath",        "Comment" },
                                  { "ListMatch",           "Search" },
                                  { "ListCursorLine",      "PmenuSel" },
                                  { "ListEndOfBuffer",     "Normal" },
                                  { "ListBorderBottom",    "Normal" },
                                  { "ListCount",           "DiagnosticVirtualTextWarn" },
                                  { "PreviewNormal",       "Normal" },
                                  { "PreviewMatch",        "Search" },
                                  { "PreviewCursorLine",   "CursorLine" },
                                  { "PreviewEndOfBuffer",  "Normal" },
                                  { "PreviewLineNr",       "LineNr" },
                                  { "PreviewBorderBottom", "Normal" },
                                  { "WinBarFilename",      "LspKindFile" },
                                  { "WinBarFilepath",      "LspKindFile" },
                                  { "WinBarTitle",         "Title" },
                          }, "Glance")
        end,
}
