local icons = {
        Array         = { icon = "󰅪", hl = "DropBarIconKindArray" },
        Boolean       = { icon = "", hl = "@lsp.type.boolean" },
        Class         = { icon = "", hl = "@lsp.type.class" },
        Component     = { icon = "󰅴", hl = "DropBarIconKindFunction" },
        Constant      = { icon = "", hl = "@lsp.type.constant" },
        Constructor   = { icon = "", hl = "@lsp.type.constructor" },
        Enum          = { icon = "", hl = "@lsp.type.enum" },
        EnumMember    = { icon = "", hl = "@lsp.type.enumMember" },
        Event         = { icon = "", hl = "@lsp.type.event" },
        Field         = { icon = "", hl = "@field" },
        File          = { icon = "", hl = "DropBarIconKindFile" },
        Fragment      = { icon = "󰅴", hl = "DropBarIconKindConstant" },
        Function      = { icon = "", hl = "@lsp.type.function" },
        Interface     = { icon = "", hl = "@lsp.type.interface" },
        Key           = { icon = "", hl = "@lsp.type.keyword" },
        Macro         = { icon = "", hl = "@lsp.type.macro" },
        Method        = { icon = "", hl = "@lsp.type.method" },
        Module        = { icon = "", hl = "@module" },
        Namespace     = { icon = "󰅪", hl = "@lsp.type.namespace" },
        Null          = { icon = "󰢤", hl = "@lsp.type.number" },
        Number        = { icon = "󰎠", hl = "@lsp.type.number" },
        Object        = { icon = "", hl = "@lsp.type.interface" },
        Operator      = { icon = "", hl = "@lsp.type.operator" },
        Package       = { icon = "", hl = "DropBarIconKindPackage" },
        Parameter     = { icon = " ", hl = "@lsp.type.parameter" },
        Property      = { icon = "", hl = "@lsp.type.property" },
        StaticMethod  = { icon = " ", hl = "@lsp.type.method" },
        String        = { icon = "󰉾", hl = "@string" },
        Struct        = { icon = "", hl = "@lsp.type.struct" },
        TypeAlias     = { icon = " ", hl = "@lsp.type.typeAlias" },
        TypeParameter = { icon = "", hl = "@lsp.type.TypeParameter" },
        Variable      = { icon = "", hl = "@lsp.type.variable" },
}

return {
        "hedyhli/outline.nvim",
        keys = { { "<LocalLeader>s", "<cmd>Outline<cr>", desc = "Outline", mode = { "n" } } },
        opts = {
                outline_window = { position = "right", width = 20, focus_on_open = false },
                outline_items  = { show_symbol_details = true, auto_set_cursor = false },
                guides         = { enabled = false },
                symbols        = { icons = icons },
                symbol_folding = {
                        autofold_depth = 1,
                        auto_unfold    = { hovered = true, only = true },
                        markers        = { Icons.Arrows.rightSmol, Icons.Arrows.downSmol },
                },
                preview_window = {
                        auto_preview = true,
                        width        = 40,
                        min_width    = 30,
                        height       = 50,
                        min_height   = 10,
                        border       = Border.borderStyle,
                        winhl        = "NormalFloat:NormalFloat",
                        winblend     = Config.blend,
                        live         = true,
                },
                keymaps        = {
                        show_help        = "?",
                        close            = { "<Esc>", "q" },
                        goto_location    = "<CR>",
                        peek_location    = "o",
                        goto_and_close   = "<S-Cr>",
                        restore_location = ",,",
                        hover_symbol     = "<C-space>",
                        toggle_preview   = "K",
                        rename_symbol    = "r",
                        code_actions     = "a",
                        fold             = "h",
                        unfold           = "l",
                        fold_toggle      = "<Tab>",
                        fold_toggle_all  = "<S-Tab>",
                        fold_all         = "H",
                        unfold_all       = "L",
                        fold_reset       = "R",
                        down_and_jump    = "J",
                        up_and_jump      = "K",
                },
        },
        config = function(_, opts)
                require("outline").setup(opts)

                local groups = {
                        { "Current",    "LspInlayHint" },
                        { "Details",    "Comment" },
                        { "FoldMarker", "Comment" },
                }
                require("core.utils").linkHl(groups, "Outline")
        end,
}
