return {
        editor   = {
                o = {
                        backup         = false,
                        swapfile       = false,
                        writebackup    = false,
                        clipboard      = "unnamedplus",
                        completeopt    = "menu,menuone,noselect",
                        ignorecase     = true,
                        nrformats      = "bin,hex,blank,unsigned",
                        smartcase      = true,
                        startofline    = false,
                        autowriteall   = false,
                        autowrite      = false,
                        confirm        = true,
                        exrc           = true,
                        formatoptions  = "",
                        grepformat     = "%f:%l:%c:%m",
                        grepprg        = "rg --vimgrep",
                        hidden         = true,
                        jumpoptions    = "stack",
                        linebreak      = false,
                        list           = true,
                        mouse          = "a",
                        mousemoveevent = true,
                        shell          = "zsh",
                        termsync       = false,
                        timeoutlen     = 500,
                        undofile       = true,
                        undolevels     = 10000,
                        whichwrap      = "<>[]hl",
                        wildmode       = "",
                        wrap           = false,
                        wrapmargin     = 120,
                        updatetime     = 2000,
                        redrawtime     = 2000,
                },
                opt = {
                        iskeyword      = vim.opt.iskeyword:append("@,48-57,_,-,192-255"),
                        sessionoptions = { "buffers", "curdir", "tabpages", "winsize", "help", "globals", "skiprtp", "folds" },
                },
        },
        ui       = {
                o = {
                        laststatus    = {
                                value = 0,
                                when  = function() return not pcall(require, "incline") or pcall(require, "dropbar") end,
                        },
                        statusline    = {
                                value = " ",
                                when  = function() return not pcall(require, "incline") or pcall(require, "dropbar") end,
                        },
                        rnu           = {
                                value = true,
                                when  = function() return vim.o.number end,
                        },
                        number        = true,
                        pumheight     = 20,
                        ruler         = false,
                        winborder     = Border.borderStyleNone,
                        cursorline    = true,
                        hlsearch      = false,
                        smoothscroll  = true,
                        termguicolors = true,
                        winminwidth   = 5,
                        inccommand    = "split",
                        pumblend      = 0,
                        shortmess     = "tF" .. "TIcC" .. "as" .. "WoO" .. "Sl",
                        showbreak     = " 󰘍 ",
                        incsearch     = true,
                        scrolloff     = 20,
                        showmode      = false,
                        sidescrolloff = 4,
                        splitbelow    = true,
                        splitright    = true,
                        foldmarker    = "[[[,]]]",
                },
                opt = {
                        guicursor = {
                                "n-v-c-sm:block-Cursor",
                                "i-ci-ve:ver25-Cursor",
                                "r-cr-o:hor20-Cursor",
                                "a:blinkwait500-blinkoff500-blinkon500",
                        },
                        fillchars = {
                                fold      = " ",
                                vert      = "│",
                                eob       = " ",
                                foldclose = Icons.Arrows.close,
                                foldopen  = Icons.Arrows.open,
                                foldsep   = "│",
                                foldinner =
                                " ",
                                diff      = "╱",
                        },
                        listchars = {
                                nbsp       = "_",
                                precedes   = Icons.Misc.ellipsis,
                                extends    = Icons.Misc.ellipsis,
                                multispace = " ",
                                lead       = " ",
                                trail      =
                                " ",
                                tab        = "  ",
                        },
                },
        },
        tabspace = {
                o = {
                        autoindent  = true,
                        shiftround  = true,
                        shiftwidth  = 8,
                        tabstop     = 2,
                        smartindent = true,
                        breakindent = true,
                        copyindent  = true,
                        expandtab   = true,
                        textwidth   = 120,
                },
        },
        spell    = {
                opt = {
                        spell        = false,
                        spelllang    = "en_us",
                        spelloptions = "noplainbuffer",
                },
        },
}
