local M = {}
------------------------------------------------------------------------------------------------------------------------

local config   = vim.fn.stdpath("config")
local readme   = config .. "/README.md"
local output   = config .. "/init.lua"
local mapfile  = config .. "/init.lua.map"
local depsfile = config .. "/dependencies.sh"
local tmp      = output .. ".tmp"
local maptmp   = mapfile .. ".tmp"
local depstmp  = depsfile .. ".tmp"

local interactive = #vim.api.nvim_list_uis() > 0

local function notify(msg, level)
        level = level or vim.log.levels.INFO
        if interactive then
                vim.notify(msg, level)
        elseif level == vim.log.levels.ERROR then
                io.stderr:write(msg .. "\n")
        else
                print(msg)
        end
end

local f = io.open(readme, "r")
if not f then
        notify("Tangle: cannot open " .. readme, vim.log.levels.ERROR)
        return
end
local content = f:read("*a")
f:close()

local blocks               = {}
local sh_blocks            = {}
local current              = nil
local current_section      = "Config"
local current_section_line = 1
local line_num             = 0

for line in (content .. "\n"):gmatch("([^\n]*)\n") do
        line_num = line_num + 1

        if current then
                if line:match("^```%s*$") then
                        local dest = current.type == "lua" and blocks or sh_blocks
                        table.insert(dest, {
                                code         = table.concat(current.lines, "\n") .. "\n",
                                line_count   = #current.lines,
                                section      = current.section,
                                section_line = current.section_line,
                        })
                        current = nil
                else
                        table.insert(current.lines, line)
                end
        elseif line:match("^#+ ") then
                current_section      = line:gsub("^#+%s+", "")
                current_section_line = line_num
        elseif line:match("^```lua") and not line:match("notangle") then
                current = {
                        type         = "lua",
                        lines        = {},
                        section      = current_section,
                        section_line = current_section_line,
                }
        elseif line:match("^```sh") and line:match("install") then
                current = {
                        type         = "sh",
                        lines        = {},
                        section      = current_section,
                        section_line = current_section_line,
                }
        end
end

local out = io.open(tmp, "w")
if not out then
        notify("Tangle: cannot write to " .. tmp, vim.log.levels.ERROR)
        return
end

local mout = io.open(maptmp, "w")
if not mout then
        out:close()
        notify("Tangle: cannot write to " .. maptmp, vim.log.levels.ERROR)
        return
end

out:write("-- Generated from README.md - do not edit directly.\n\n")

local map_entries = {}
local next_line   = 3

for _, block in ipairs(blocks) do
        out:write("-- [" .. block.section .. "]\n")

        local code_start = next_line + 1
        out:write(block.code)
        out:write("\n")

        local code_end = code_start + block.line_count - 1

        table.insert(map_entries, {
                init_start  = code_start,
                init_end    = code_end,
                readme_line = block.section_line,
                section     = block.section,
        })

        next_line = code_end + 2
end

out:close()

mout:write("-- Source map: init.lua line ranges → README.md section headings.\n")
mout:write("-- Generated by tangle.lua — do not edit directly.\n")
mout:write("return {\n")
for _, e in ipairs(map_entries) do
        mout:write(string.format(
                "  { init_start=%3d, init_end=%3d, readme_line=%3d, section=%q },\n",
                e.init_start, e.init_end, e.readme_line, e.section))
end
mout:write("}\n")
mout:close()

local bout = io.open(depstmp, "w")
if not bout then
        notify("Tangle: cannot write to " .. depstmp, vim.log.levels.ERROR)
        return
end

bout:write("#!/usr/bin/env bash\n")
bout:write("# dependencies.sh - install system dependencies for this Neovim config.\n")
bout:write("# Generated from README.md by tangle.lua - do not edit directly.\n")
bout:write("# Requires Neovim to already be installed. See README.md for setup flow.\n")
bout:write("\n")
bout:write("set -euo pipefail\n")
bout:write("\n")
bout:write("if command -v apt-get &>/dev/null; then\n")
bout:write("    PKG() { sudo apt-get install -y \"$@\"; }\n")
bout:write("    sudo apt-get update -qq\n")
bout:write("elif command -v pacman &>/dev/null; then\n")
bout:write("    PKG() { sudo pacman -S --noconfirm \"$@\"; }\n")
bout:write("elif command -v brew &>/dev/null; then\n")
bout:write("    PKG() { brew install \"$@\"; }\n")
bout:write("else\n")
bout:write("    echo 'No supported package manager found (apt, pacman, brew).' >&2\n")
bout:write("    exit 1\n")
bout:write("fi\n")

for _, block in ipairs(sh_blocks) do
        bout:write("\n# [" .. block.section .. "]\n")
        bout:write(block.code)
end

bout:close()

local ok, err = loadfile(tmp)
if not ok then
        vim.fn.delete(tmp)
        vim.fn.delete(maptmp)
        vim.fn.delete(depstmp)
        notify("Tangle FAILED - fix the error below, then save again:\n" .. err,
               vim.log.levels.ERROR)
        return
end

vim.fn.rename(tmp,     output)
vim.fn.rename(maptmp,  mapfile)
vim.fn.rename(depstmp, depsfile)

notify(string.format(
        "Tangled %d lua blocks → init.lua, %d sh blocks → dependencies.sh — restart Neovim to apply",
        #blocks, #sh_blocks))

------------------------------------------------------------------------------------------------------------------------
return M
